### ISSUE TITLE
Data Fetching : custom hook useRequest to fetch data

### ISSUE THREAD

**Issue by cinfinit** [cinfinit/react-approaches-pratices#1]
Add one of the basic way to fetch data in react .  Showcase the same in a separate route . Follow the guidelines for more info

**Comment by nalin-programmer** [comment]
Assign me this task

**Comment by cinfinit** [comment]
Sure , though i hope you have read the guidelines . Assigning  :) happy coding

**Comment by rparthas** [comment]
I can do this. Basically we can useRequest to fetch some data and then pass that data to another route. Would that be helpful ?

**Comment by cinfinit** [comment]
yeah , that could be one way to approach it . Wanna work on this issue then ?

**Comment by cinfinit** [comment]
@rparthas , yeah , that could be one way to approach it . Wanna work on this issue then ?

**Comment by rparthas** [comment]
Sure assign to me

**Comment by cinfinit** [comment]
hey @rparthas  , can you tell the progress on this ?

**Comment by rparthas** [comment]
Will complete by this weekend

**Comment by cinfinit** [comment]
@rparthas sure , let me know the status at possible intervals

**Comment by rparthas** [comment]
I have done the ahooks useRequest using https://dog.ceo/dog-api/breeds-list. I have to add documentation and then use another route to display image of a dog. Will give a pull request once done. created a folder for hooks and moved the entire pet pages under pages/pets. Should be ready with pull request tomorrow

**Comment by cinfinit** [comment]
Used ahooks approach to implement this by @rparthas .
